sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/InternalError__c.field-meta.xml
<CustomField>
    <fullName>InternalError__c</fullName>
    <description>If Apex classes threw an exception during the process of the integration, the error message and stack trace will be filled here</description>
    <label>Internal Error</label>
    <length>2042</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/MuleIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegrationName__c</fullName>
    <description>Mule Integration custom metadata name. This is a constant used in the integration architecture.</description>
    <label>MuleIntegrationName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload that will be published and builded by Salesforce integration architecture.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Id of the master record that will be integrated</description>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/MuleIntegration__mdt.object-meta.xml
<CustomObject>
    <description>All known integrations and it&apos;s configurations with MuleSoft will be registered in this custom metadata.</description>
    <label>Mule Integration</label>
    <pluralLabel>Mule Integrations</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/MuleIntegrationEvent__e.object-meta.xml
<CustomObject>
    <description>MuleSoft event driven architecture integrations</description>
    <label>Mule Integration Event</label>
    <pluralLabel>MuleIntegrationEvent</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/MuleEventQueueId__c.field-meta.xml
<CustomField>
    <fullName>MuleEventQueueId__c</fullName>
    <description>MuleEventQueue__c Id related to the Platform Event. The object MuleEventQueue__c is the responsible for logging and operating all integrations life-cycle.</description>
    <label>MuleEventQueueId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/MuleIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegrationName__c</fullName>
    <description>Integration name is a constant used in the platform events integration accelerator</description>
    <label>MuleIntegrationName</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload that will be sent on Event publishing</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/MuleIntegrationObject__mdt.object-meta.xml
<CustomObject>
    <description>All the objects types and fields that will be integrated related to a Mule Integration</description>
    <label>Mule Integration Object</label>
    <pluralLabel>Mule Integration Objects</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Fields from this Object that will be integrated (if they are filled)</description>
    <label>Fields</label>
    <length>2046</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/MuleIntegration__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegration__c</fullName>
    <description>Related Mule Integration</description>
    <label>Mule Integration</label>
    <referenceTo>MuleIntegration__mdt</referenceTo>
    <relationshipLabel>Integration Objects</relationshipLabel>
    <relationshipName>MuleIntegrationObjects</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>SObject Type API Name, ex: Account or YourCustomObject__c</description>
    <label>SObject Type</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleIntegrationCommand.cls
/**
 * @description: Abstract command class that contains common methods for Mule Integration commands
 * @author: Henrique Bustillos - Everymind
 */
public abstract class MuleIntegrationCommand {

    protected MuleIntegration__mdt integration;

    protected MuleEventQueueRepository muleEventQueueRepository;

    protected MuleIntegrationRepository muleIntegrationRepository;

    protected MuleIntegrationValidator validate;

    public MuleIntegrationCommand ( MuleIntegrationType integrationType ) {
        this();
        this.setIntegration( integrationType );
    }

    protected MuleIntegrationCommand () {
        this.muleEventQueueRepository = new MuleEventQueueRepository();
        this.muleIntegrationRepository = new MuleIntegrationRepository();
        this.validate = new MuleIntegrationValidator();
    }

    @TestVisible
    private void setIntegration ( MuleIntegrationType integrationType ) {

        this.integration = this.muleIntegrationRepository.findByIntegrationName( integrationType );

        this.validate.existantMetadata( this.integration );
        this.validate.objectsNotEmpty( this.integration );
        this.validate.objectsFieldsNotEmpty( this.integration.MuleIntegrationObjects__r );
    }

    public virtual List<Database.SaveResult> execute () {
        return this.execute( this.muleEventQueueRepository.findPendingByIntegrationName( this.integration.DeveloperName ) );
    }

    public abstract List<Database.SaveResult> execute (List<MuleEventQueue__c> eventQueues);

    protected void updateEventQueuesWithError(List<MuleEventQueue__c> eventQueues, String message) {

        for ( MuleEventQueue__c eventQueue : eventQueues ) {
            this.enrichEventQueueWithError( eventQueue, message );
        }

        this.muleEventQueueRepository.save(eventQueues);
    }

    protected Map<String, String> getFieldsByObjectName () {

        Map<String, String> fieldsByObjectName = new Map<String, String>();

        for ( MuleIntegrationObject__mdt integrationObject : this.integration.MuleIntegrationObjects__r ) {

            fieldsByObjectName.put(
                integrationObject.SObjectType__c,
                integrationObject.Fields__c
            );
        }

        return fieldsByObjectName;
    }

    protected MuleEventQueue__c enrichEventQueueWithError ( MuleEventQueue__c eventQueue, String message ) {

        String errorPayload = JSON.serializePretty( message );

        eventQueue.Status__c = MuleEventQueueStatus.ERROR.name();
        eventQueue.InternalError__c = errorPayload;

        return eventQueue;
    }

    protected List<MuleEventQueue__c> withPayloadOrError ( List<MuleEventQueue__c> eventQueues, Map<String, Object> payloadByObjectId ) {

        for ( MuleEventQueue__c eventQueue : eventQueues ) {

            if ( !payloadByObjectId.containsKey( eventQueue.RecordId__c ) ) {
                eventQueue = this.enrichEventQueueWithError( eventQueue, 'Record in RecordId__c field not found.');
                continue;
            }

            eventQueue.Payload__c = JSON.serialize( payloadByObjectId.get( eventQueue.RecordId__c ) );
        }

        return eventQueues;
    }

    protected MuleIntegrationEvent__e buildEvent ( MuleEventQueue__c eventQueue ) {

        return new MuleIntegrationEvent__e (
            MuleIntegrationName__c = eventQueue.MuleIntegrationName__c
            , MuleEventQueueId__c = eventQueue.Id
            , Payload__c = eventQueue.Payload__c
        );
    }

    protected List<Database.SaveResult> publishEvents ( List<MuleEventQueue__c> eventQueues ) {

        List<MuleIntegrationEvent__e> eventsToPublish = new List<MuleIntegrationEvent__e>();

        for ( MuleEventQueue__c eventQueue : eventQueues ) {

            if ( eventQueue.Status__c == MuleEventQueueStatus.ERROR.name() ) continue;

            eventsToPublish.add( this.buildEvent( eventQueue ) );
        }

        this.muleEventQueueRepository.save( eventQueues );

        if ( eventsToPublish.isEmpty() ) return null;

        return EventBus.publish( eventsToPublish );
    }

    @TestVisible
    private void setMuleEventQueueRepository ( MuleEventQueueRepository muleEventQueueRepository ) {
        this.muleEventQueueRepository = muleEventQueueRepository;
    }

    @TestVisible
    private void setMuleIntegrationRepository ( MuleIntegrationRepository muleIntegrationRepository ) {
        this.muleIntegrationRepository = muleIntegrationRepository;
    }
}