sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/IsRetryBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsRetryBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this event was retryed the limit number of retries or if another event was created for the same record this field will be checked automatically by the framework</description>
    <label>IsRetryBlocked</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueFactory.cls
/**
 * @description: This class is a factory for Event Queue objects to use exclusively in test contexts.
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleEventQueueFactory {

    public static MuleEventQueue__c newMuleEventQueue () {
        return new MuleEventQueue__c (
            IsRetryBlocked__c = false
            , RetryCount__c = 0
            , Status__c = MuleEventQueueStatus.PENDING.name()
            , ObjectId__c = 'fakeId'
        );
    }

    public static MuleEventQueue__c newMuleEventQueue ( MuleIntegration__c integration ) {

        MuleEventQueue__c eventQueue = newMuleEventQueue();
        eventQueue.MuleIntegration__c = integration.Id;

        return eventQueue;
    }

    public static MuleEventQueue__c createMuleEventQueue ( MuleIntegration__c integration ) {
        return createMuleEventQueue( newMuleEventQueue( integration ) );
    }

    public static MuleEventQueue__c createMuleEventQueue () {
        return createMuleEventQueue( newMuleEventQueue( MuleIntegrationFactory.createMuleIntegration() ) );
    }

    public static MuleEventQueue__c createMuleEventQueue (MuleEventQueue__c eventQueue) {
        insert eventQueue;
        return eventQueue;
    }

    public static MuleEventQueue__c fromJson ( String payload ) {
        return (MuleEventQueue__c) JSON.deserialize( payload, MuleEventQueue__c.class );
    }

    public static List<MuleEventQueue__c> fromJsonArray ( String payload ) {
        return (List<MuleEventQueue__c>) JSON.deserialize( payload, List<MuleEventQueue__c>.class );
    }
}