sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/IsRetryBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsRetryBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this event was retryed the limit number of retries or if another event was created for the same record this field will be checked automatically by the framework</description>
    <label>IsRetryBlocked</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/MuleIntegration__mdt.object-meta.xml
<CustomObject>
    <description>All known integrations and it&apos;s configurations with MuleSoft will be registered in this custom metadata.</description>
    <label>Mule Integration</label>
    <pluralLabel>Mule Integrations</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/classes/MuleEventQueueFilterTest.cls
/**
 * @description: Test class for MuleEventQueueFilter
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleEventQueueFilterTest {

    @isTest
    static void returnEventsWhenFilterByInactiveIntegrations() {

        List<MuleEventQueue__c> muleEventQueues = new MuleEventQueue__c[]{ MuleEventQueueFactory.newMuleEventQueue() };

        Map<String, MuleIntegration__mdt> integrations = MuleIntegrationFactory.newIntegrations();

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byInactiveIntegrations( muleEventQueues, integrations );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Filtered event queues should have 1 element' );
    }

    @isTest
    static void returnEventWhenFilterNewPendingByDuplicityValidables () {

        String eventQueuesPayload = '[{ "Status__c": "PENDING" }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray(eventQueuesPayload);

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byDuplicityValidables( muleEventQueues, new Map<Id, MuleEventQueue__c>() );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Filtered event queues should have 1 element' );
    }

    @isTest
    static void returnEventWhenFilterUpdatedByDuplicityValidables () {

        String eventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "PENDING", "IsRetryBlocked__c": false }]';

        String oldEventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "PENDING", "IsRetryBlocked__c": true }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray(eventQueuesPayload);

        Map<Id, MuleEventQueue__c> oldEventQueuesById = new Map<Id, MuleEventQueue__c>(
            MuleEventQueueFactory.fromJsonArray(oldEventQueuesPayload)
        );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byDuplicityValidables( muleEventQueues, oldEventQueuesById );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'There should not have duplicity validables event queues' );
    }

    @isTest
    static void returnEventWhenFilterCanceledToPendingByDuplicityValidables () {

        String eventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "PENDING" }]';

        String oldEventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "CANCELED" }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray(eventQueuesPayload);

        Map<Id, MuleEventQueue__c> oldEventQueuesById = new Map<Id, MuleEventQueue__c>(
            MuleEventQueueFactory.fromJsonArray(oldEventQueuesPayload)
        );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byDuplicityValidables( muleEventQueues, oldEventQueuesById );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Filtered event queues should have 1 element' );
    }

    @isTest
    static void returnEventWhenFilterPendingToSentByDuplicityValidables () {

        String eventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "SENT" }]';

        String oldEventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "PENDING" }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray(eventQueuesPayload);

        Map<Id, MuleEventQueue__c> oldEventQueuesById = new Map<Id, MuleEventQueue__c>(
            MuleEventQueueFactory.fromJsonArray(oldEventQueuesPayload)
        );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byDuplicityValidables( muleEventQueues, oldEventQueuesById );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Duplicity validables event queues should have 1 element' );
    }

    @isTest
    static void returnEmptyWhenFilterSentToTechnicalErrorByDuplicityValidables () {

        String eventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "TECHNICAL_ERROR" }]';

        String oldEventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "SENT" }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray(eventQueuesPayload);

        Map<Id, MuleEventQueue__c> oldEventQueuesById = new Map<Id, MuleEventQueue__c>(
            MuleEventQueueFactory.fromJsonArray(oldEventQueuesPayload)
        );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byDuplicityValidables( muleEventQueues, oldEventQueuesById );

        Test.stopTest();

        System.assert( filteredEventQueues.isEmpty(), 'There should not have any duplicity validables queues.' );
    }

    @isTest
    static void itShouldReturnPendingEventQueues() {

        String payload = '[{ "Status__c": "PENDING" }, { "Status__c": "CANCELED" }]';

        List<MuleEventQueue__c> muleEventQueues = MuleEventQueueFactory.fromJsonArray( payload );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byPendingEventQueues( muleEventQueues );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Filtered event queues should have 1 element' );
    }

    @isTest
    static void itShouldReturnRetryedEventQueues() {

        String payload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "SUCCESS" }, { "Id": "a1K890000003A1FEAU", "Status__c": "PENDING" }]';

        String oldEventQueuesPayload = '[{ "Id": "a1K8900000039y1EAA", "Status__c": "TECHNICAL_ERROR" }, { "Id": "a1K890000003A1FEAU", "Status__c": "CANCELED" }]';

        List<MuleEventQueue__c> newEventQueues = MuleEventQueueFactory.fromJsonArray( payload );

        Map<Id, MuleEventQueue__c> oldEventQueues = new Map<Id, MuleEventQueue__c>( MuleEventQueueFactory.fromJsonArray( oldEventQueuesPayload ) );

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredEventQueues = filter.byRetryedEventQueues( newEventQueues, oldEventQueues );

        Test.stopTest();

        Assert.areEqual( 1, filteredEventQueues.size(), 'Filtered event queues should have 1 element' );
    }

    @isTest
    static void returnEventsWithEmptyStatus() {

        MuleEventQueue__c eventQueue = MuleEventQueueFactory.newMuleEventQueue();
        eventQueue.Status__c = null;

        List<MuleEventQueue__c> muleEventQueues = new List<MuleEventQueue__c>{ eventQueue };

        Test.startTest();

        MuleEventQueueFilter filter = new MuleEventQueueFilter();

        List<MuleEventQueue__c> filteredQueues = filter.byEmptyStatus( muleEventQueues );

        Test.stopTest();

        Assert.areEqual( 1, filteredQueues.size(), 'Filtered event queues should have 1 element' );
    }
}