sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/IsRetryBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsRetryBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this event was retryed the limit number of retries or if another event was created for the same record this field will be checked automatically by the framework</description>
    <label>IsRetryBlocked</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/MuleIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegrationName__c</fullName>
    <description>Mule Integration custom metadata name. This is a constant used in the integration architecture.</description>
    <label>MuleIntegrationName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Id of the master record that will be integrated</description>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueRepository.cls
/**
 * @description: This class provides collections of stored Mule Event Queues
 * @author: Henrique Bustillos - Everymind
 */
public virtual inherited sharing class MuleEventQueueRepository extends Repository {

    public virtual List<MuleEventQueue__c> findPendingByRecordsIds (Set<String> recordsIds, List<String> ignoredIds) {
        return this.findPendingByRecordsIds( new List<String>(recordsIds), ignoredIds );
    }

    public virtual List<MuleEventQueue__c> findPendingByRecordsIds (List<String> recordsIds, List<String> ignoredIds) {
        return [
            SELECT Id, RecordId__c, Status__c, CreatedDate, LastModifiedDate
            FROM MuleEventQueue__c
            WHERE RecordId__c IN :recordsIds
            AND Status__c = :MuleEventQueueStatus.PENDING.name()
            AND Id NOT IN :ignoredIds
            ORDER BY CreatedDate ASC
        ];
    }

    public virtual List<MuleEventQueue__c> findPendingByIntegrationName ( String integrationName ) {
        return [
            SELECT Id, RecordId__c, Status__c, CreatedDate, LastModifiedDate, MuleIntegrationName__c
            FROM MuleEventQueue__c
            WHERE Status__c = :MuleEventQueueStatus.PENDING.name()
            AND MuleIntegrationName__c = :integrationName
            ORDER BY CreatedDate ASC
        ];
    }

    public virtual List<MuleEventQueue__c> findRetryable ( Set<String> retryableIntegrationsNames ) {
        return [
            SELECT Id, RecordId__c, Status__c, CreatedDate, LastModifiedDate, RetryCount__c, IsRetryBlocked__c, MuleIntegrationName__c
            FROM MuleEventQueue__c
            WHERE Status__c = :MuleEventQueueStatus.TECHNICAL_ERROR.name()
            AND MuleIntegrationName__c IN :retryableIntegrationsNames
            AND RetryCount__c < 3
            AND IsRetryBlocked__c = false
        ];
    }

    public virtual List<MuleEventQueue__c> findOldRelated ( List<String> objectsIds, List<String> ignoredEventsQueuesIds ) {
        return [
            SELECT Id, RecordId__c, Status__c, CreatedDate, LastModifiedDate, RetryCount__c, IsRetryBlocked__c, MuleIntegrationName__c
            FROM MuleEventQueue__c
            WHERE Status__c != :MuleEventQueueStatus.PENDING.name()
            AND RecordId__c IN :objectsIds
            AND Id NOT IN :ignoredEventsQueuesIds
            AND IsRetryBlocked__c = false
            AND LastModifiedDate > :Date.today().addDays(-15)
        ];
    }

    public virtual List<MuleEventQueue__c> findByIds ( List<String> ids ) {
        return [
            SELECT Id, Status__c
            FROM MuleEventQueue__c
            WHERE Id IN :ids
        ];
    }

}