sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/InternalError__c.field-meta.xml
<CustomField>
    <fullName>InternalError__c</fullName>
    <description>If Apex classes threw an exception during the process of the integration, the error message and stack trace will be filled here</description>
    <label>Internal Error</label>
    <length>2042</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload that will be published and builded by Salesforce integration architecture.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Id of the master record that will be integrated</description>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/ReturnedPayload__c.field-meta.xml
<CustomField>
    <fullName>ReturnedPayload__c</fullName>
    <description>Returned payload that will be upserted by MuleSoft automatically</description>
    <label>Returned Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueHandlerTest.cls
/**
 * @description: Test class for MuleEventQueueHandler
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleEventQueueHandlerTest {

    @isTest
    static void itShouldCreateAnEventQueue() {

        Test.startTest();

        MuleEventQueue__c muleEventQueue = MuleEventQueueFactory.createMuleEventQueue();

        Test.stopTest();

        List<MuleEventQueue__c> storedEventQueues = [SELECT Id FROM MuleEventQueue__c WHERE Id = :muleEventQueue.Id];

        System.assertEquals( 1, storedEventQueues.size(), 'There should be one event queue created');
    }

    @isTest
    static void itShoulReturnAnErrorWhenCreatingDuplicatedEventQueue() {

        MuleEventQueue__c muleEventQueue = MuleEventQueueFactory.createMuleEventQueue();

        Test.startTest();

        try {

            MuleEventQueue__c newEventQueue = MuleEventQueueFactory.createMuleEventQueue();

            System.assert( false, 'There should be an error' );

        } catch ( DmlException e ) {

            System.assert( true, 'There should be an error' );
        }

        Test.stopTest();
    }

    @isTest
    static void itShouldCreateAnSchedulableEventQueue() {

        MuleEventQueue__c muleEventQueue = MuleEventQueueFactory.createMuleEventQueue();

        MuleEventQueue__c newEventQueue = MuleEventQueueFactory.newMuleEventQueue();
        newEventQueue.RecordId__c = 'anotherObjectId';

        Test.startTest();

        MuleEventQueueFactory.createMuleEventQueue( newEventQueue );

        Test.stopTest();

        List<MuleEventQueue__c> storedEventQueues = [SELECT Id FROM MuleEventQueue__c WHERE Id = :newEventQueue.Id];

        System.assertEquals( 1, storedEventQueues.size(), 'There should return the event queue created');
    }

    @isTest
    static void itShouldResetAnEventQueue() {

        MuleEventQueue__c muleEventQueue = MuleEventQueueFactory.newMuleEventQueue();
        muleEventQueue.Status__c = MuleEventQueueStatus.SENT.name();
        muleEventQueue.ReturnedPayload__c = 'payload';
        muleEventQueue.Payload__c = 'payload';
        muleEventQueue.InternalError__c = 'null';
        insert muleEventQueue;

        Test.startTest();

        muleEventQueue.Status__c = '';
        update muleEventQueue;

        Test.stopTest();

        List<MuleEventQueue__c> storedEventQueues = [SELECT Id, Status__c, ReturnedPayload__c, Payload__c, InternalError__c FROM MuleEventQueue__c WHERE Id = :muleEventQueue.Id];

        Assert.areEqual( 1, storedEventQueues.size(), 'There should be one event queue created and updated');

        Assert.areEqual( MuleEventQueueStatus.PENDING.name(), storedEventQueues[0].Status__c, 'Should be PENDING' );
        Assert.areEqual( null, storedEventQueues[0].ReturnedPayload__c, 'ReturnedPayload__c Should be reseted' );
        Assert.areEqual( null, storedEventQueues[0].Payload__c, 'Payload__c Should be reseted' );
        Assert.areEqual( null, storedEventQueues[0].InternalError__c, 'InternalError__c Should be reseted' );
    }
}