sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/InternalError__c.field-meta.xml
<CustomField>
    <fullName>InternalError__c</fullName>
    <description>If Apex classes threw an exception during the process of the integration, the error message and stack trace will be filled here</description>
    <label>Internal Error</label>
    <length>2042</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/IsRetryBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsRetryBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this event was retryed the limit number of retries or if another event was created for the same record this field will be checked automatically by the framework</description>
    <label>IsRetryBlocked</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/MuleIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegrationName__c</fullName>
    <description>Mule Integration custom metadata name. This is a constant used in the integration architecture.</description>
    <label>MuleIntegrationName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload that will be published and builded by Salesforce integration architecture.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/ReturnedPayload__c.field-meta.xml
<CustomField>
    <fullName>ReturnedPayload__c</fullName>
    <description>Returned payload that will be upserted by MuleSoft automatically</description>
    <label>Returned Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/MuleIntegrationEvent__e.object-meta.xml
<CustomObject>
    <description>MuleSoft event driven architecture integrations</description>
    <label>Mule Integration Event</label>
    <pluralLabel>MuleIntegrationEvent</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/MuleEventQueueId__c.field-meta.xml
<CustomField>
    <fullName>MuleEventQueueId__c</fullName>
    <description>MuleEventQueue__c Id related to the Platform Event. The object MuleEventQueue__c is the responsible for logging and operating all integrations life-cycle.</description>
    <label>MuleEventQueueId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/MuleIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegrationName__c</fullName>
    <description>Integration name is a constant used in the platform events integration accelerator</description>
    <label>MuleIntegrationName</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload that will be sent on Event publishing</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueEnricherTest.cls
/**
 * @description: Test class for MuleEventQueueEnricher
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleEventQueueEnricherTest {

    @isTest
    static void returnCanceledEvent () {

        String eventQueuePayload = '[{ "Status__c": "PENDING" }]';

        List<MuleEventQueue__c> queuesToCancel = MuleEventQueueFactory.fromJsonArray( eventQueuePayload );

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();

        List<MuleEventQueue__c> canceledQueues = enricher.cancel( queuesToCancel );

        Test.stopTest();

        Assert.areEqual( MuleEventQueueStatus.CANCELED.name(), canceledQueues.get(0).Status__c, 'Mule Event Queue status should be CANCELED' );
    }

    @isTest
    static void itShouldBlockEventQueue () {

        String eventQueuePayload = '{ "IsRetryBlocked__c": false }';

        MuleEventQueue__c eventQueue = MuleEventQueueFactory.fromJson( eventQueuePayload );

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();

        MuleEventQueue__c enrichedQueue = enricher.blockRetry( eventQueue );

        Test.stopTest();

        System.assert( enrichedQueue.IsRetryBlocked__c, 'IsRetryBlocked__c should be true' );
    }

    @isTest
    static void itShouldBlockEventQueues () {

        String eventQueuesPayload = '[{ "IsRetryBlocked__c": false }]';

        List<MuleEventQueue__c> eventQueues = MuleEventQueueFactory.fromJsonArray( eventQueuesPayload );

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();
        enricher.setRepository( new MuleEventQueueRepositoryTest.MuleEventQueueRepositoryMock() );

        List<MuleEventQueue__c> enrichedQueues = enricher.blockRetries( eventQueues );

        Test.stopTest();

        System.assert( enrichedQueues.get(0).IsRetryBlocked__c, 'IsRetryBlocked__c should be true' );
    }

    @isTest
    static void itShouldincrementRetryCount () {

        String eventQueuesPayload = '[{ "RetryCount__c": 2, "IsRetryBlocked__c": false }, { "RetryCount__c": 0, "IsRetryBlocked__c": false }]';

        List<MuleEventQueue__c> eventQueues = MuleEventQueueFactory.fromJsonArray( eventQueuesPayload );

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();
        enricher.setRepository( new MuleEventQueueRepositoryTest.MuleEventQueueRepositoryMock() );

        List<MuleEventQueue__c> enrichedQueues = enricher.incrementRetryCount( eventQueues );

        Test.stopTest();

        System.assert( enrichedQueues.get(0).IsRetryBlocked__c, 'IsRetryBlocked__c should be true' );
        Assert.areEqual( 3, enrichedQueues.get(0).RetryCount__c, 'RetryCount__c should be 3' );

        System.assert( !enrichedQueues.get(1).IsRetryBlocked__c, 'IsRetryBlocked__c should be false' );
        Assert.areEqual( 1, enrichedQueues.get(1).RetryCount__c, 'RetryCount__c should be 1' );
    }

    @isTest
    static void updatePublishedEvents() {

        TriggerHandler.bypass('MuleEventQueueHandler');

        MuleEventQueue__c eventQueue = MuleEventQueueFactory.createMuleEventQueue();

        TriggerHandler.clearBypass('MuleEventQueueHandler');

        MuleIntegrationEvent__e event = new MuleIntegrationEvent__e();
        event.MuleEventQueueId__c = eventQueue.Id;
        event.MuleIntegrationName__c = eventQueue.MuleIntegrationName__c;

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();
        enricher.setRepository( new MuleEventQueueRepositoryTest.MuleEventQueueRepositoryMock() );

        List<MuleEventQueue__c> savedQueues = enricher.updatePublishedEvents( new List<MuleIntegrationEvent__e>{ event } );

        Test.stopTest();

        Assert.isFalse( savedQueues.isEmpty(), 'Should not be empty' );
        Assert.areEqual( 1, savedQueues.size(), 'Size should be 1' );
    }

    @isTest
    static void setPendingStatusAndResetFields() {

        MuleEventQueue__c eventQueue = MuleEventQueueFactory.newMuleEventQueue();
        eventQueue.Status__c = null;
        eventQueue.ReturnedPayload__c = 'payload';
        eventQueue.Payload__c = 'payload';
        eventQueue.InternalError__c = 'error';

        List<MuleEventQueue__c> eventQueues = new List<MuleEventQueue__c>{ eventQueue };

        Test.startTest();

        MuleEventQueueEnricher enricher = new MuleEventQueueEnricher();

        List<MuleEventQueue__c> enrichedQueues = enricher.withPendingStatus( eventQueues );

        Test.stopTest();

        Assert.isFalse( enrichedQueues.isEmpty(), 'Should not be empty' );
        Assert.areEqual( enrichedQueues.size(), 1, 'Should be 1' );

        Assert.areEqual( MuleEventQueueStatus.PENDING.name(), enrichedQueues[0].Status__c, 'Should be PENDING' );
        Assert.areEqual( '', enrichedQueues[0].ReturnedPayload__c, 'Should be reseted' );
        Assert.areEqual( '', enrichedQueues[0].Payload__c, 'Should be reseted' );
        Assert.areEqual( '', enrichedQueues[0].InternalError__c, 'Should be reseted' );
    }
}