sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Id of the master record that will be integrated</description>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueValidatorTest.cls
/**
 * @description: Test class for MuleEventQueueValidator
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleEventQueueValidatorTest {

    @isTest
    static void scenarioWithExistentPendingObjectId() {

        List<MuleEventQueue__c> muleEventQueues = new List<MuleEventQueue__c>{ MuleEventQueueFactory.newMuleEventQueue() };

        List<String> exitentObjectsIds = new List<String>{ muleEventQueues.get(0).RecordId__c };

        Test.startTest();

        MuleEventQueueValidator validator = new MuleEventQueueValidator();

        validator.withNotDuplicatedObjectId( muleEventQueues , exitentObjectsIds );

        Test.stopTest();

        System.assert( muleEventQueues.get(0).hasErrors(), 'EventQueue should have error' );
    }

    @isTest
    static void scenarioWithDuplicatedInSameContext() {

        List<MuleEventQueue__c> muleEventQueues = new List<MuleEventQueue__c>{
            MuleEventQueueFactory.newMuleEventQueue(),
            MuleEventQueueFactory.newMuleEventQueue()
        };

        Test.startTest();

        MuleEventQueueValidator validator = new MuleEventQueueValidator();

        validator.withNotDuplicatedObjectId( muleEventQueues , new List<String>() );

        Test.stopTest();

        System.assert( muleEventQueues.get(1).hasErrors(), 'EventQueue should have error' );
    }
}