sfdc-integration-accelerator/src/objects/MuleEventQueue__c/MuleEventQueue__c.object-meta.xml
<CustomObject>
    <description>All mule events that triggered the life-cycle of an integration.</description>
    <label>Mule Event Queue</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Mule Event Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/IsRetryBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsRetryBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this event was retryed the limit number of retries or if another event was created for the same record this field will be checked automatically by the framework</description>
    <label>IsRetryBlocked</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleEventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
                <default>true</default>
                <label>PENDING</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
            <value>
                <fullName>TECHNICAL_ERROR</fullName>
            </value>
            <value>
                <fullName>BUSINESS_ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleEventQueueEnricher.cls
/**
 * @description: Class to enrich Mule Event Queues with information. Generally used in a trigger transaction.
 * @author: Henrique Bustillos - Everymind
 */
public without sharing class MuleEventQueueEnricher {

    MuleEventQueueRepository repository;

    public MuleEventQueueEnricher() {
        this.repository = new MuleEventQueueRepository();
    }

    public List<MuleEventQueue__c> cancel ( List<MuleEventQueue__c> eventQueues ) {

        for ( MuleEventQueue__c eventQueue : eventQueues ) {
            this.cancel( eventQueue );
        }

        return eventQueues;
    }

    public MuleEventQueue__c cancel ( MuleEventQueue__c eventQueue ) {

        eventQueue.Status__c = MuleEventQueueStatus.CANCELED.name();

        return eventQueue;
    }

    public MuleEventQueue__c blockRetry ( MuleEventQueue__c eventQueue ) {

        eventQueue.IsRetryBlocked__c = true;

        return eventQueue;
    }

    public List<MuleEventQueue__c> blockRetries ( List<MuleEventQueue__c> oldRelatedEventQueues ) {

        for ( MuleEventQueue__c oldRelatedEventQueue : oldRelatedEventQueues ) {
            this.blockRetry( oldRelatedEventQueue );
        }

        return this.repository.save( oldRelatedEventQueues );
    }

    public List<MuleEventQueue__c> incrementRetryCount ( List<MuleEventQueue__c> newEventQueues ) {

        for( MuleEventQueue__c eventQueue : newEventQueues ) {

            eventQueue.RetryCount__c += 1;

            if (eventQueue.RetryCount__c >= 3) {
                this.blockRetry( eventQueue );
            }
        }

        return newEventQueues;
    }

    @TestVisible
    private void setRepository ( MuleEventQueueRepository repository ) {
        this.repository = repository;
    }
}