sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/MuleIntegration__mdt.object-meta.xml
<CustomObject>
    <description>All known integrations and it&apos;s configurations with MuleSoft will be registered in this custom metadata.</description>
    <label>Mule Integration</label>
    <pluralLabel>Mule Integrations</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <description>Apex class name that will be ran to process the Platform Event integration (publishing).</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Integration description, what is it?</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define if integration should be triggered</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/fields/IsRetryable__c.field-meta.xml
<CustomField>
    <fullName>IsRetryable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define if the integration will be retryed automatically when occurs Technical Errors returned in the mule events queues.</description>
    <label>IsRetryable</label>
    <type>Checkbox</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/MuleIntegrationObject__mdt.object-meta.xml
<CustomObject>
    <description>All the objects types and fields that will be integrated related to a Mule Integration</description>
    <label>Mule Integration Object</label>
    <pluralLabel>Mule Integration Objects</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Fields from this Object that will be integrated (if they are filled)</description>
    <label>Fields</label>
    <length>2046</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/MuleIntegration__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegration__c</fullName>
    <description>Related Mule Integration</description>
    <label>Mule Integration</label>
    <referenceTo>MuleIntegration__mdt</referenceTo>
    <relationshipLabel>Integration Objects</relationshipLabel>
    <relationshipName>MuleIntegrationObjects</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>SObject Type API Name, ex: Account or YourCustomObject__c</description>
    <label>SObject Type</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleIntegrationFactory.cls
/**
 * @description: Factory class to provide MuleIntegration__mdt for tests
 * @author: Henrique Bustillos - Everymind
 */
@isTest
public class MuleIntegrationFactory {

    public static String getIntegrationPayload() {
        return getIntegrationPayload('');
    }

    public static String getIntegrationPayload( String integrationObjects ) {
        return '{ "ApexClassName__c":"MuleIntegrationCommandTest.MuleIntegrationCommandMock", "IsActive__c": false, "Label": "'+ MuleEventQueueFactory.TEST_INTEGRATION +'", '
            + '"IsRetryable__c":true, "MasterLabel":"'+ MuleEventQueueFactory.TEST_INTEGRATION +'", '
            + '"SystemModstamp":"2023-01-01T00:00:00.000+0000", "Language":"pt_BR", "IsSchedulable__c":true, '
            + '"Description__c":"Test integration metadata.", "QualifiedApiName":"'+ MuleEventQueueFactory.TEST_INTEGRATION +'", '
            + '"DeveloperName":"'+ MuleEventQueueFactory.TEST_INTEGRATION +'"'+ integrationObjects +' }';
    }

    public static String getIntegrationWithObjectsAndFieldsPayload( String fields ) {

        String integrationObjects = ', "MuleIntegrationObjects__r": {"totalSize":1, "done":true,'
        + '"records": [{"attributes": {"type": "MuleIntegrationObject__mdt"}, "Fields__c": "'+fields+'",'
        + '"SObjectType__c": "Account", "DeveloperName": "TestIntegrationAccount"}]}';

        return getIntegrationPayload( integrationObjects );
    }

    public static String getIntegrationWithObjectsAndFieldsPayload( String fields, String sObjectType ) {

        String integrationObjects = ', "MuleIntegrationObjects__r": {"totalSize":1, "done":true,'
        + '"records": [{"attributes": {"type":"MuleIntegrationObject__mdt"}, "Fields__c":"'+fields+'",'
        + '"SObjectType__c": "'+sObjectType+'", "DeveloperName": "TestIntegrationAccount"}]}';

        return getIntegrationPayload( integrationObjects );
    }

    public static MuleIntegration__mdt newMuleIntegration() {
        return fromJson( getIntegrationPayload('') );
    }

    public static MuleIntegration__mdt newMuleIntegrationWithObjects() {

        return fromJson( getIntegrationWithObjectsAndFieldsPayload('') );
    }

    public static MuleIntegration__mdt newMuleIntegrationWithObjectsAndFields() {

        return fromJson( getIntegrationWithObjectsAndFieldsPayload('Name') );
    }

    public static Map<String, MuleIntegration__mdt> newIntegrations() {

        Map<String, MuleIntegration__mdt> integrations = new Map<String, MuleIntegration__mdt>();

        integrations.put(MuleEventQueueFactory.TEST_INTEGRATION, newMuleIntegration());

        return integrations;
    }

    public static MuleIntegration__mdt fromJson( String payload ) {
        return (MuleIntegration__mdt) JSON.deserialize( payload, MuleIntegration__mdt.class);
    }
}