sfdc-integration-accelerator/src/objects/MuleIntegration__mdt/MuleIntegration__mdt.object-meta.xml
<CustomObject>
    <description>All known integrations and it&apos;s configurations with MuleSoft will be registered in this custom metadata.</description>
    <label>Mule Integration</label>
    <pluralLabel>Mule Integrations</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/MuleIntegrationObject__mdt.object-meta.xml
<CustomObject>
    <description>All the objects types and fields that will be integrated related to a Mule Integration</description>
    <label>Mule Integration Object</label>
    <pluralLabel>Mule Integration Objects</pluralLabel>
</CustomObject>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Fields from this Object that will be integrated (if they are filled)</description>
    <label>Fields</label>
    <length>2046</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-integration-accelerator/src/objects/MuleIntegrationObject__mdt/fields/MuleIntegration__c.field-meta.xml
<CustomField>
    <fullName>MuleIntegration__c</fullName>
    <description>Related Mule Integration</description>
    <label>Mule Integration</label>
    <referenceTo>MuleIntegration__mdt</referenceTo>
    <relationshipLabel>Integration Objects</relationshipLabel>
    <relationshipName>MuleIntegrationObjects</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-integration-accelerator/src/classes/MuleIntegrationValidator.cls
/**
 * @description: Responsible to Validate mule integration metadatas
 * @author: Henrique Bustillos - Everymind
 */
public without sharing class MuleIntegrationValidator {

    public void emptyRecords ( List<SObject> records ) {

        if ( records.isEmpty() ) {

            throw new MuleIntegrationException('No target records to process');
        }
    }

    public void emptyRecords ( Map<String, Object> records ) {

        if ( records.isEmpty() ) {

            throw new MuleIntegrationException('No target records to process');
        }
    }

    public void existantMetadata ( MuleIntegration__mdt integration ) {

        if ( integration == null ) {

            throw new MuleIntegrationException('Integration metadata does not exist');
        }
    }

    public void objectsNotEmpty ( MuleIntegration__mdt integration ) {

        if ( integration.MuleIntegrationObjects__r.isEmpty() ) {

            throw new MuleIntegrationException('Integration metadata does not have objects associated');
        }
    }

    public void objectsFieldsNotEmpty ( List<MuleIntegrationObject__mdt> integrationObjects ) {

        for ( MuleIntegrationObject__mdt integrationObject : integrationObjects ) {

            if ( integrationObject.Fields__c == null || integrationObject.Fields__c == '' ) {

                throw new MuleIntegrationException('Integration metadata object does not have fields filled');
            }
        }
    }
}